### ISSUE TITLE
No deals matched

### ISSUE THREAD

**Issue by facadev** [sonm-io/core#360]
In the current MVP phase, is there any statistics available on how long it takes before a deal can be matched on average? I set up all the components, created an ask bid and waited for long, yet no deal was struck.

BTW, is there any telegram channel for dev?

**Comment by 3Hren** [comment]
Hi!

Unfortunately, currently there is no way to achieve this, except parsing logs. However we have plans to collect various metrics in the nearest future, including wait-time for proposing a deal.

**Comment by facadev** [comment]
Understood. Keep up the good work.

**Comment by iolebedev** [comment]
Hello.

The reason behind waiting for the deal to be closed is the following: this is market. For your deal to be matched there must be an ASK order on the market. Looks like at this moment all hardware suppliers are providing their resources for test and for themselves. This is because the current payment is in test tokens. This will change with time.

At this moment you may consider establishing a hub and provisioning resources on your own for a test.
