### ISSUE TITLE
Worker service as root

### ISSUE THREAD

**Issue by cedbale** [sonm-io/core#473]
In 3.2.0 version i need now to run worker service as root to avoid this error
```
ERROR   miner/main.go:61        cannot create worker instance   {"error": "cannot initialize volume plugin \"cifs\": mkdir /run/docker/plugins: permission denied"}
```
is it mandatory to run this process with root privileges ?

**Comment by 3Hren** [comment]
Hi!

It is highly recommended for worker to be run with root privileges, because it requires the following capabilities:
- Communication with Docker (including via plugins - what you've seen).
- Managing additional cgroups to be able to restrict resource usage for itself.

And it's likely that this list will only be expanded in the future with overlay networks support and iptables handling.

However you can anyway configure the worker for running without sudo, look at `plugins` section of `worker.yaml` and the way how Docker [discoveres and communitates](https://docs.docker.com/engine/extend/plugin_api/) with plugins.
