### ISSUE TITLE
Miner/hub daemon config

### ISSUE THREAD

**Issue by iolebedev** [sonm-io/core#7]
Create miner/hub daemon configurable ability
- common package for common parsers/options, hub/miner have their own interfaces
- json (yaml?)
- shipped params: all existing params and keys fom CLI (IP, ports, etc)

**Comment by 3Hren** [comment]
I'd personally prefer YAML for the following reasons:
- It's compact.
- It allows comments. After maintaining a REALLY big configurations (which is obviously grows through the time) it becomes write-only even for developers. Self-explanatory configurations is a big win.
- If you like JSON - you're welcome too, since [JSON is a subset of YAML](http://eli.thegreenplace.net/2008/11/22/json-yaml-but-yaml-json).

Cons:
- Well, almost all random number of symbols appears to be valid YAML.

**Comment by iolebedev** [comment]
Let's go for YAML then.

**Comment by Sokel** [comment]
may i request one option field:
named: "bootnodes"
type: array of strings
thanks.

**Comment by sshaman1101** [comment]
#16 Work in progress, review required;

**Comment by Sokel** [comment]
Merged #16
