### ISSUE TITLE
Feature: Allow users to connect to the network through a proxy (e.g. socks5)

### ISSUE THREAD

**Issue by MeijeSibbel** [sonm-io/core#99]

**Comment by iolebedev** [comment]
Hi @MeijeSibbel 

Sorry for so late reply.

The system has many components, namely: hub, worker, client, market, locator and later other services. The internal communication is working over gRPC, which uses HTTP/2.0 and requires persistent connection. However if we talk about public proxies, supporting persistent connections seems limited (it is not beneficial kind of proxy use cases). If we talk about enterprise environment, use case for proxies seems like not really necessary, because can be worked around.

So, if you still consider this as a viable idea, please feel free to propose additional explanations and reasoning:
- What is the main use case for working through proxies? Who will use it and why?
- Are there any companies, that would use SONM if we do this and otherwise not?
- Which of the components would you like to see working through proxy?
- Which proxies do you see as usable, except Socks5?
- Any additional info as you see it.

**Comment by iolebedev** [comment]
Ok, in the proposed way this seems irrelevant. Feel free to get back with arguments.
